- name: Update peer DNS records
  hosts: localhost
  gather_facts: false
  become: true
  become_method: doas

  vars:
    jrun_include: /var/unbound/conf.d/jrun.conf
    jrun_domain: jrun

  tasks:
    - name: Update peers block in DNS config
      ansible.builtin.blockinfile:
        path: "{{ jrun_include }}"
        marker: "# {mark} jrun-peers"
        block: |
          {% for peer in peers | default([]) %}
          {% for j in peer.jails %}
              local-data: "{{ j.name }}.{{ peer.alias }}.{{ jrun_domain }}. IN AAAA {{ j.ygg_address }}"
          {% endfor %}
          {% endfor %}
      register: peers_changed

    - name: Validate local_unbound config
      ansible.builtin.command: local-unbound-checkconf
      changed_when: false
      when: peers_changed.changed

    - name: Reload local_unbound
      ansible.builtin.command: service local_unbound reload
      when: peers_changed.changed
