- name: Install app requirements
  hosts: localhost
  gather_facts: false

  vars:
    python_ver: "3.14"
    python_bin: "/usr/local/bin/python{{ python_ver }}"

  tasks:
    - name: Export requirements 
      ansible.builtin.command: >
        uv export --frozen --no-dev --no-hashes --no-emit-project --format requirements-txt -o /tmp/reqs.txt
      args:
        chdir: /srv/app

    - name: Install requirements
      ansible.builtin.shell: >
        {{ python_bin }} -m pip install -r /tmp/reqs.txt
